// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),

ACMD_DEF(autopilot),
ACMD_DEF(autopilotsp),
ACMD_DEF(autosong),
ACMD_DEF(autosong2),
ACMD_DEF(autosong3),
ACMD_DEF(autoconc),
ACMD_DEF(autopilothom),
ACMD_DEF(autoelem),
ACMD_DEF(autopilotdist),
